export default {
	ONBOARD: 'ONBOARD',
	FINISHED: 'FINISHED',
	PROCESSING: 'PROCESSING',
	AUTHENTICATE: 'AUTHENTICATE',
	GET_LOANS: 'GET_LOANS',
	REQUEST_LOAN: 'REQUEST_LOAN',
	PAY_LOAN: 'PAY_LOAN',
	GET_ACCOUNTS: 'GET_ACCOUNTS',
	REVEAL_BVN: 'REVEAL_BVN',
};